version: '3.8'

services:
  postgresql:
    image: 'postgres:15'
    restart: always
    container_name: postgres
    build: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blockchain

